// ============================================================
//  lib/datos/sugerencias.ts  —  Sugerencias de rutas y paquetes
// ============================================================

import type { Sugerencia, Paquete, Nivel } from '../tipos';

// ===========================
//  SUGERENCIAS DE RUTAS
// ===========================

export const SUGERENCIAS_RUTAS: Sugerencia[] = [
  // ── QUINTANA ROO ──────────────────────────────────────────────────────────
  { id: 'Quintana Roo|premium',   titulo: 'Tulum de Lujo',        estado: 'Quintana Roo',       hotel: 'Wakax Hacienda Cenote',        precioHotel: 'Desde $3,000/noche', estilo: 'Lujo, naturaleza',         restaurante: 'Rosa Negra',                  precioRestaurante: '$2,000/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/tulum/800/600' },
  { id: 'Quintana Roo|medio',     titulo: 'Cancún & Playa',       estado: 'Quintana Roo',       hotel: 'Marriott Cancún Resort',       precioHotel: 'Desde $2,200/noche', estilo: 'Playa, resort',            restaurante: 'El Fish Fritanga',            precioRestaurante: '$500/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/cancun/800/600' },
  { id: 'Quintana Roo|economico', titulo: 'Riviera Maya',         estado: 'Quintana Roo',       hotel: 'Hostal Cozumel',               precioHotel: 'Desde $400/noche',   estilo: 'Playa, mochilero',         restaurante: 'El Pescador',                 precioRestaurante: '$150/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/riviera/800/600' },
  // ── YUCATÁN ───────────────────────────────────────────────────────────────
  { id: 'Yucatán|premium',        titulo: 'Mérida Exclusiva',     estado: 'Yucatán',            hotel: 'Chablé Resort & Spa',          precioHotel: 'Desde $4,500/noche', estilo: 'Lujo maya contemporáneo',  restaurante: "Ixi'im Restaurant",           precioRestaurante: '$1,800/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/merida/800/600' },
  { id: 'Yucatán|medio',          titulo: 'Chichén Itzá',         estado: 'Yucatán',            hotel: 'Hotel Mayaland',               precioHotel: 'Desde $1,800/noche', estilo: 'Cultural, histórico',      restaurante: 'Hacienda Chichén',            precioRestaurante: '$800/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/chichenitza/800/600' },
  { id: 'Yucatán|economico',      titulo: 'Mérida Colonial',      estado: 'Yucatán',            hotel: 'Hostal Nomadas',               precioHotel: 'Desde $320/noche',   estilo: 'Cultural, colonial',       restaurante: 'La Chaya Maya',               precioRestaurante: '$150/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/merida2/800/600' },
  // ── CHIAPAS ───────────────────────────────────────────────────────────────
  { id: 'Chiapas|premium',        titulo: 'Palenque VIP',         estado: 'Chiapas',            hotel: 'Na Bolom Lodge',               precioHotel: 'Desde $2,800/noche', estilo: 'Lujo, selva lacandona',    restaurante: 'La Viña de Bacco',            precioRestaurante: '$900/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/palenque/800/600' },
  { id: 'Chiapas|medio',          titulo: 'San Cristóbal',        estado: 'Chiapas',            hotel: 'Hotel Casa Mexicana',          precioHotel: 'Desde $980/noche',   estilo: 'Colonial, artesanal',      restaurante: 'TierrAdentro',                precioRestaurante: '$380/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/sancristobal/800/600' },
  { id: 'Chiapas|economico',      titulo: 'Cañón del Sumidero',   estado: 'Chiapas',            hotel: 'Hostal Río Lacanjá',           precioHotel: 'Desde $350/noche',   estilo: 'Naturaleza, aventura',     restaurante: 'El Fogón de Jovel',           precioRestaurante: '$120/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/sumidero/800/600' },
  // ── OAXACA ────────────────────────────────────────────────────────────────
  { id: 'Oaxaca|premium',         titulo: 'Oaxaca Gourmet',       estado: 'Oaxaca',             hotel: 'Casa Oaxaca Hotel',            precioHotel: 'Desde $3,200/noche', estilo: 'Gastronomía de autor',     restaurante: 'Alcalá by R. Castellanos',    precioRestaurante: '$1,500/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/oaxaca/800/600' },
  { id: 'Oaxaca|medio',           titulo: 'Monte Albán',          estado: 'Oaxaca',             hotel: 'Casa Oaxaca',                  precioHotel: 'Desde $2,200/noche', estilo: 'Cultural, gastronómico',   restaurante: 'Los Danzantes',               precioRestaurante: '$1,200/persona', nivel: 'medio',    imagen: 'https://picsum.photos/seed/monteAlban/800/600' },
  { id: 'Oaxaca|economico',       titulo: 'Oaxaca Artesanal',     estado: 'Oaxaca',             hotel: 'Hostal Casa del Río',          precioHotel: 'Desde $380/noche',   estilo: 'Arte, mole, mezcal',       restaurante: 'Mercado Benito Juárez',       precioRestaurante: '$100/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/oaxaca3/800/600' },
  // ── CIUDAD DE MÉXICO ──────────────────────────────────────────────────────
  { id: 'Ciudad de México|premium',  titulo: 'CDMX de Lujo',      estado: 'Ciudad de México',   hotel: 'Gran Hotel CDMX',              precioHotel: 'Desde $4,000/noche', estilo: 'Lujo, urbano, histórico',  restaurante: 'Azul Histórico',              precioRestaurante: '$1,500/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/cdmx/800/600' },
  { id: 'Ciudad de México|medio',    titulo: 'Coyoacán & Museos', estado: 'Ciudad de México',   hotel: 'Hotel del Carmen',             precioHotel: 'Desde $900/noche',   estilo: 'Arte, bohemio',            restaurante: 'Los Danzantes Coyoacán',      precioRestaurante: '$500/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/coyoacan/800/600' },
  { id: 'Ciudad de México|economico',titulo: 'Centro Histórico',  estado: 'Ciudad de México',   hotel: 'Hotel Isabel',                 precioHotel: 'Desde $450/noche',   estilo: 'Historia, streetfood',     restaurante: 'Café El Popular',             precioRestaurante: '$120/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/centrohistorico/800/600' },
  // ── JALISCO ───────────────────────────────────────────────────────────────
  { id: 'Jalisco|premium',        titulo: 'Guadalajara Premium',  estado: 'Jalisco',            hotel: 'One Hotel Guadalajara',        precioHotel: 'Desde $2,800/noche', estilo: 'Diseño, tradición tapatía',restaurante: 'Alcalde',                     precioRestaurante: '$1,200/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/guadalajara/800/600' },
  { id: 'Jalisco|medio',          titulo: 'Guadalajara',          estado: 'Jalisco',            hotel: 'Hotel Morales',                precioHotel: 'Desde $1,200/noche', estilo: 'Tradición, tapatío',       restaurante: 'La Chata',                    precioRestaurante: '$400/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/guadalajara2/800/600' },
  { id: 'Jalisco|economico',      titulo: 'Pueblo Tequila',       estado: 'Jalisco',            hotel: 'Hotel Solar de las Ánimas',    precioHotel: 'Desde $900/noche',   estilo: 'Cultural, gastronómico',   restaurante: 'La Antigua Casona',           precioRestaurante: '$500/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/tequila/800/600' },
  // ── GUANAJUATO ────────────────────────────────────────────────────────────
  { id: 'Guanajuato|premium',     titulo: 'San Miguel Allende',   estado: 'Guanajuato',         hotel: 'Hotel Rosewood San Miguel',    precioHotel: 'Desde $4,200/noche', estilo: 'Arte, lujo colonial',      restaurante: 'Moxi by Enrique Olvera',      precioRestaurante: '$1,400/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/sanmiguel/800/600' },
  { id: 'Guanajuato|medio',       titulo: 'Guanajuato Ciudad',    estado: 'Guanajuato',         hotel: 'Hotel Boutique 1850',          precioHotel: 'Desde $1,100/noche', estilo: 'Colonial, minero',         restaurante: 'La Capellina',                precioRestaurante: '$500/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/guanajuato/800/600' },
  { id: 'Guanajuato|economico',   titulo: 'Festival Cervantino',  estado: 'Guanajuato',         hotel: 'Hostal Cantarranas',           precioHotel: 'Desde $350/noche',   estilo: 'Cultural, callejones',     restaurante: 'Truco 7',                     precioRestaurante: '$130/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/cervantino/800/600' },
  // ── GUERRERO ──────────────────────────────────────────────────────────────
  { id: 'Guerrero|premium',       titulo: 'Acapulco VIP',         estado: 'Guerrero',           hotel: 'Hotel Las Brisas Premium',     precioHotel: 'Desde $3,500/noche', estilo: 'Lujo, playa clásica',      restaurante: 'Pez Vela',                    precioRestaurante: '$900/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/acapulco/800/600' },
  { id: 'Guerrero|medio',         titulo: 'Acapulco',             estado: 'Guerrero',           hotel: 'Hotel Las Brisas',             precioHotel: 'Desde $1,800/noche', estilo: 'Playa, aventura',          restaurante: 'El Amigo Miguel',             precioRestaurante: '$600/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/acapulco2/800/600' },
  { id: 'Guerrero|economico',     titulo: 'Zihuatanejo',          estado: 'Guerrero',           hotel: 'Posada La Noria',              precioHotel: 'Desde $500/noche',   estilo: 'Playa tranquila',          restaurante: 'El Patio',                    precioRestaurante: '$220/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/zihuatanejo/800/600' },
  // ── PUEBLA ────────────────────────────────────────────────────────────────
  { id: 'Puebla|premium',         titulo: 'Puebla Gourmet',       estado: 'Puebla',             hotel: 'NH Collection Puebla',         precioHotel: 'Desde $2,500/noche', estilo: 'Alta cocina, historia',    restaurante: 'Ephimera',                    precioRestaurante: '$1,100/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/puebla/800/600' },
  { id: 'Puebla|medio',           titulo: 'Centro Histórico',     estado: 'Puebla',             hotel: 'Hotel Camino Real Puebla',     precioHotel: 'Desde $1,400/noche', estilo: 'Colonial, cultural',       restaurante: 'La China Poblana',            precioRestaurante: '$500/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/puebla2/800/600' },
  { id: 'Puebla|economico',       titulo: 'Cholula & Pirámide',   estado: 'Puebla',             hotel: 'Hostal Allende',               precioHotel: 'Desde $300/noche',   estilo: 'Historia, cerveza artesanal',restaurante: 'Fonda Santa Clara',           precioRestaurante: '$150/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/cholula/800/600' },
  // ── VERACRUZ ──────────────────────────────────────────────────────────────
  { id: 'Veracruz|premium',       titulo: 'Veracruz Premium',     estado: 'Veracruz',           hotel: 'Galería Plaza Veracruz',       precioHotel: 'Desde $2,000/noche', estilo: 'Puerto, historia',         restaurante: 'Villa Rica Mocambo',          precioRestaurante: '$800/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/veracruz/800/600' },
  { id: 'Veracruz|medio',         titulo: 'Tajín & Costa',        estado: 'Veracruz',           hotel: 'Hotel Misión Papantla',        precioHotel: 'Desde $900/noche',   estilo: 'Arqueología, playa',       restaurante: 'El Tajín Restaurant',         precioRestaurante: '$300/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/tajin/800/600' },
  { id: 'Veracruz|economico',     titulo: 'Puerto Jarocho',       estado: 'Veracruz',           hotel: 'Hotel Emporio Veracruz',       precioHotel: 'Desde $1,200/noche', estilo: 'Cultural, playa',          restaurante: 'Gran Café de la Parroquia',   precioRestaurante: '$400/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/veracruz3/800/600' },
  // ── MICHOACÁN ─────────────────────────────────────────────────────────────
  { id: 'Michoacán|premium',      titulo: 'Pátzcuaro Boutique',   estado: 'Michoacán',          hotel: 'Hotel Villa Montaña',          precioHotel: 'Desde $2,600/noche', estilo: 'Lujo, cultura purépecha',  restaurante: 'Don Vasco Restaurant',        precioRestaurante: '$900/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/patzcuaro/800/600' },
  { id: 'Michoacán|medio',        titulo: 'Pátzcuaro & Monarca',  estado: 'Michoacán',          hotel: 'Hotel Mansión Iturbe',         precioHotel: 'Desde $950/noche',   estilo: 'Cultural, monarca',        restaurante: 'El Patio',                    precioRestaurante: '$350/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/patzcuaro2/800/600' },
  { id: 'Michoacán|economico',    titulo: 'Santuario Mariposas',  estado: 'Michoacán',          hotel: 'Hostal La Catedral Morelia',   precioHotel: 'Desde $350/noche',   estilo: 'Naturaleza, artesanías',   restaurante: 'Las Mercedes',                precioRestaurante: '$150/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/monarca/800/600' },
  // ── SINALOA ───────────────────────────────────────────────────────────────
  { id: 'Sinaloa|premium',        titulo: 'Mazatlán Zona Dorada', estado: 'Sinaloa',            hotel: 'Hotel El Cid Marina',          precioHotel: 'Desde $2,100/noche', estilo: 'Playa, carnaval, lujo',    restaurante: 'Angelo\'s Restaurant',        precioRestaurante: '$800/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/mazatlan/800/600' },
  { id: 'Sinaloa|medio',          titulo: 'Mazatlán',             estado: 'Sinaloa',            hotel: 'Hotel Playa Mazatlán',         precioHotel: 'Desde $800/noche',   estilo: 'Playa, carnaval',          restaurante: 'Pedro & Lola',                precioRestaurante: '$450/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/mazatlan2/800/600' },
  { id: 'Sinaloa|economico',      titulo: 'Mazatlán Histórico',   estado: 'Sinaloa',            hotel: 'Hotel Sinaloa Centro',         precioHotel: 'Desde $420/noche',   estilo: 'Centro histórico, playa',  restaurante: 'El Presidio',                 precioRestaurante: '$180/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/mazatlan3/800/600' },
  // ── QUERÉTARO ─────────────────────────────────────────────────────────────
  { id: 'Querétaro|premium',      titulo: 'Querétaro Boutique',   estado: 'Querétaro',          hotel: 'La Casa de la Marquesa',       precioHotel: 'Desde $2,800/noche', estilo: 'Colonial, vinos finos',    restaurante: 'La Viña del Marqués',         precioRestaurante: '$1,000/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/queretaro/800/600' },
  { id: 'Querétaro|medio',        titulo: 'Peña de Bernal',       estado: 'Querétaro',          hotel: 'Meson de Bernal',              precioHotel: 'Desde $1,100/noche', estilo: 'Colonial, viticola',       restaurante: 'El Mezquite',                 precioRestaurante: '$420/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/bernal/800/600' },
  { id: 'Querétaro|economico',    titulo: 'Querétaro Histórico',  estado: 'Querétaro',          hotel: 'Hostal 1810',                  precioHotel: 'Desde $380/noche',   estilo: 'Callejones, historia',     restaurante: 'La Flor de Querétaro',        precioRestaurante: '$160/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/queretaro3/800/600' },
  // ── SAN LUIS POTOSÍ ───────────────────────────────────────────────────────
  { id: 'San Luis Potosí|premium',titulo: 'Huasteca Premium',     estado: 'San Luis Potosí',    hotel: 'Real de Minas SLP',            precioHotel: 'Desde $2,100/noche', estilo: 'Naturaleza de lujo',       restaurante: 'La Corriente Cebichería',     precioRestaurante: '$900/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/huasteca/800/600' },
  { id: 'San Luis Potosí|medio',  titulo: 'Cascadas Huasteca',    estado: 'San Luis Potosí',    hotel: 'Hotel Valles',                 precioHotel: 'Desde $900/noche',   estilo: 'Cascadas, naturaleza',     restaurante: 'El Callejón',                 precioRestaurante: '$300/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/cascadas/800/600' },
  { id: 'San Luis Potosí|economico',titulo: 'Xilitla Surrealista',estado: 'San Luis Potosí',    hotel: 'Posada El Castillo',           precioHotel: 'Desde $420/noche',   estilo: 'Surrealismo, selva',       restaurante: 'Café Inglés',                 precioRestaurante: '$130/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/xilitla/800/600' },
  // ── NUEVO LEÓN ────────────────────────────────────────────────────────────
  { id: 'Nuevo León|premium',     titulo: 'Monterrey Business',   estado: 'Nuevo León',         hotel: 'Galería Plaza Monterrey',      precioHotel: 'Desde $3,200/noche', estilo: 'Negocios, gastronomía regia',restaurante: 'Pangea',                    precioRestaurante: '$1,200/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/monterrey/800/600' },
  { id: 'Nuevo León|medio',       titulo: 'Monterrey Cultural',   estado: 'Nuevo León',         hotel: 'Hotel Ancira Hyatt',           precioHotel: 'Desde $1,600/noche', estilo: 'Arte, sierra, urbano',     restaurante: 'El Rey del Cabrito',          precioRestaurante: '$700/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/monterrey2/800/600' },
  { id: 'Nuevo León|economico',   titulo: 'Barrio Antiguo MTY',   estado: 'Nuevo León',         hotel: 'Hostal MTY',                   precioHotel: 'Desde $400/noche',   estilo: 'Barrio Antiguo, cañones',  restaurante: 'Taquitos el Tío',             precioRestaurante: '$180/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/barrioAntiguo/800/600' },
  // ── BAJA CALIFORNIA ───────────────────────────────────────────────────────
  { id: 'Baja California|premium',titulo: 'Valle de Guadalupe',   estado: 'Baja California',    hotel: 'Bruma Restaurant & Hotel',     precioHotel: 'Desde $3,800/noche', estilo: 'Enoturismo de lujo',       restaurante: 'Fauna by David Castro',       precioRestaurante: '$1,600/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/guadalupe/800/600' },
  { id: 'Baja California|medio',  titulo: 'Ensenada & Vinos',     estado: 'Baja California',    hotel: 'Hotel Misión Santa Isabel',    precioHotel: 'Desde $1,300/noche', estilo: 'Vinos, mariscos',          restaurante: 'Manzanilla',                  precioRestaurante: '$600/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/ensenada/800/600' },
  { id: 'Baja California|economico',titulo: 'Tijuana Gastronómica',estado: 'Baja California',   hotel: 'Hotel Lucerna Tijuana',        precioHotel: 'Desde $700/noche',   estilo: 'Gastronomía urbana',       restaurante: 'Caesar\'s Restaurant',        precioRestaurante: '$250/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/tijuana/800/600' },
  // ── BAJA CALIFORNIA SUR ───────────────────────────────────────────────────
  { id: 'Baja California Sur|premium',  titulo: 'Los Cabos Premium',   estado: 'Baja California Sur', hotel: 'The Cape Thompson',       precioHotel: 'Desde $8,000/noche', estilo: 'Ultra lujo, yates, surf',  restaurante: 'El Farallón',                 precioRestaurante: '$2,500/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/loscabos/800/600' },
  { id: 'Baja California Sur|medio',    titulo: 'La Paz & Ballenas',   estado: 'Baja California Sur', hotel: 'Hotel Seven Crown La Paz',precioHotel: 'Desde $1,600/noche', estilo: 'Mar de Cortés, naturaleza', restaurante: 'El Bismarkcito',              precioRestaurante: '$500/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/lapaz/800/600' },
  { id: 'Baja California Sur|economico',titulo: 'Loreto & Misiones',   estado: 'Baja California Sur', hotel: 'Hostal Junipero',         precioHotel: 'Desde $500/noche',   estilo: 'Historia, kayak',          restaurante: 'La Palapa',                   precioRestaurante: '$180/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/loreto/800/600' },
  // ── HIDALGO ───────────────────────────────────────────────────────────────
  { id: 'Hidalgo|medio',          titulo: 'Prismas Basálticos',   estado: 'Hidalgo',            hotel: 'Camino Real Pachuca',          precioHotel: 'Desde $1,100/noche', estilo: 'Naturaleza, haciendas',    restaurante: 'El Mesón',                    precioRestaurante: '$300/persona',   nivel: 'medio',     imagen: 'https://picsum.photos/seed/prismas/800/600' },
  { id: 'Hidalgo|economico',      titulo: 'Mineral del Monte',    estado: 'Hidalgo',            hotel: 'Posada Real Mineral del Monte', precioHotel: 'Desde $500/noche',  estilo: 'Pueblo mágico, pastes',    restaurante: 'Cantina Real',                precioRestaurante: '$130/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/mineral/800/600' },
  // ── NAYARIT ───────────────────────────────────────────────────────────────
  { id: 'Nayarit|premium',        titulo: 'Punta Mita Exclusiva', estado: 'Nayarit',            hotel: 'Four Seasons Punta Mita',      precioHotel: 'Desde $7,000/noche', estilo: 'Lujo absoluto, surf',      restaurante: 'Ketsi',                       precioRestaurante: '$2,000/persona', nivel: 'premium',  imagen: 'https://picsum.photos/seed/puntamita/800/600' },
  { id: 'Nayarit|medio',          titulo: 'Sayulita Surf',        estado: 'Nayarit',            hotel: 'Hotel Boutique DOMe',          precioHotel: 'Desde $1,500/noche', estilo: 'Surf, pueblo artesanal',   restaurante: 'Don Pedro\'s',                precioRestaurante: '$450/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/sayulita/800/600' },
  { id: 'Nayarit|economico',      titulo: 'Sayulita Mochilera',   estado: 'Nayarit',            hotel: 'Hostal Weliwel',               precioHotel: 'Desde $350/noche',   estilo: 'Playa, hippie, surf',      restaurante: 'El Itacate',                  precioRestaurante: '$140/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/sayulita2/800/600' },
  // ── SONORA ────────────────────────────────────────────────────────────────
  { id: 'Sonora|premium',         titulo: 'San Carlos Premium',   estado: 'Sonora',             hotel: 'Hotel Marbella San Carlos',    precioHotel: 'Desde $2,400/noche', estilo: 'Mar de Cortés, pesca',     restaurante: 'El Marinero',                 precioRestaurante: '$800/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/sancarlos/800/600' },
  { id: 'Sonora|medio',           titulo: 'Puerto Peñasco',       estado: 'Sonora',             hotel: 'Hotel Peñasco del Sol',        precioHotel: 'Desde $1,200/noche', estilo: 'Playa, Mar de Cortés',     restaurante: 'La Curva',                    precioRestaurante: '$400/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/penasco/800/600' },
  { id: 'Sonora|economico',       titulo: 'Álamos Pueblo Mágico', estado: 'Sonora',             hotel: 'Posada de los Tesoros',        precioHotel: 'Desde $550/noche',   estilo: 'Colonial, historia minera',restaurante: 'El Mesón la Hacienda',        precioRestaurante: '$200/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/alamos/800/600' },
  // ── CHIHUAHUA ─────────────────────────────────────────────────────────────
  { id: 'Chihuahua|premium',      titulo: 'Barrancas del Cobre VIP',estado: 'Chihuahua',        hotel: 'Posada del Cobre',             precioHotel: 'Desde $3,500/noche', estilo: 'Aventura de lujo',         restaurante: 'El Divisadero Restaurant',    precioRestaurante: '$900/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/cobre/800/600' },
  { id: 'Chihuahua|medio',        titulo: 'Barrancas Cobre',      estado: 'Chihuahua',          hotel: 'Hotel Misión',                 precioHotel: 'Desde $1,400/noche', estilo: 'Aventura, rarámuris',      restaurante: 'Tarahumara Restaurant',       precioRestaurante: '$450/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/cobre2/800/600' },
  { id: 'Chihuahua|economico',    titulo: 'Chihuahua Capital',    estado: 'Chihuahua',          hotel: 'Hotel San Juan',               precioHotel: 'Desde $500/noche',   estilo: 'Historia, desierto',       restaurante: 'La Calesa de Pancho Villa',   precioRestaurante: '$200/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/chihuahua/800/600' },
  // ── COLIMA ────────────────────────────────────────────────────────────────
  { id: 'Colima|medio',           titulo: 'Volcán de Colima',     estado: 'Colima',             hotel: 'Hotel Las Candelas',           precioHotel: 'Desde $1,000/noche', estilo: 'Volcán, mar pacífico',     restaurante: 'Los Naranjos',                precioRestaurante: '$350/persona',   nivel: 'medio',     imagen: 'https://picsum.photos/seed/volcan/800/600' },
  { id: 'Colima|economico',       titulo: 'Manzanillo Playero',   estado: 'Colima',             hotel: 'Posada La Tortuga',            precioHotel: 'Desde $450/noche',   estilo: 'Playa, pesca, descanso',   restaurante: 'El Fogón',                    precioRestaurante: '$160/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/manzanillo/800/600' },
  // ── MORELOS ───────────────────────────────────────────────────────
  { id: 'Morelos|medio',          titulo: 'Cuernavaca Histórica', estado: 'Morelos',            hotel: 'Hotel Cortés Cuernavaca',      precioHotel: 'Desde $1,300/noche', estilo: 'Historia, jardines',       restaurante: 'La India Bonita',             precioRestaurante: '$400/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/cuernavaca/800/600' },
  { id: 'Morelos|economico',      titulo: 'Balnearios de Morelos',estado: 'Morelos',            hotel: 'Posada Cuauhtémoc',            precioHotel: 'Desde $400/noche',   estilo: 'Balnearios, relajación',   restaurante: 'Fonda Recreativa',            precioRestaurante: '$130/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/balnearios/800/600' },
  // ── ZACATECAS ─────────────────────────────────────────────────────────────
  { id: 'Zacatecas|premium',      titulo: 'Zacatecas Colonial',   estado: 'Zacatecas',          hotel: 'Quinta Real Zacatecas',        precioHotel: 'Desde $3,000/noche', estilo: 'Hacienda, vinos, historia',restaurante: 'El Recoveco',                 precioRestaurante: '$900/persona',   nivel: 'premium',  imagen: 'https://picsum.photos/seed/zacatecas/800/600' },
  { id: 'Zacatecas|medio',        titulo: 'Casco Histórico',      estado: 'Zacatecas',          hotel: 'Hotel Emporio Zacatecas',      precioHotel: 'Desde $1,200/noche', estilo: 'Mining, colonial, arte',   restaurante: 'El Jacalito',                 precioRestaurante: '$380/persona',   nivel: 'medio',    imagen: 'https://picsum.photos/seed/zacatecas2/800/600' },
  { id: 'Zacatecas|economico',    titulo: 'Zacatecas Minas',      estado: 'Zacatecas',          hotel: 'Hostal del Centro',            precioHotel: 'Desde $380/noche',   estilo: 'Teleférico, plata',        restaurante: 'La Cuija',                    precioRestaurante: '$150/persona',   nivel: 'economico', imagen: 'https://picsum.photos/seed/zacatecas3/800/600' },
];

// ===========================
//  PAQUETES POR ESTADO
// ===========================

export const PAQUETES_POR_ESTADO: Record<string, Paquete[]> = {
  'Chiapas': [
    { nivel:'economico', color:'#3AB7A5', emoji:'$', precioTotal:'$2,500 MXN', hotel:'Hostal Río Lacanjá', estrellas:2, precioHotel:'$350 MXN / noche',
      descripcionHotel:{ es:'Hostal acogedor en el centro de San Cristóbal, con vista a los cerros y desayuno incluido.', en:'Cozy hostel in the heart of San Cristóbal, with hill views and breakfast included.' },
      incluye:{ es:['WiFi gratuito','Desayuno continental','Casilleros seguros'], en:['Free WiFi','Continental breakfast','Secure lockers'] },
      restaurante:'El Fogón de Jovel', tipoCocina:{ es:'Comida típica chiapaneca', en:'Traditional Chiapan cuisine' }, precioRestaurante:'$120 MXN por persona',
      platillo:{ es:'Tasajo con frijoles y tortillas hechas a mano', en:'Tasajo with beans and handmade tortillas' },
      transporte:{ es:'Combi local + caminatas', en:'Local minibus + walks' }, precioTransporte:'$80 MXN / día',
      actividades:{ es:['Cañón del Sumidero en lancha','Mercado de Santo Domingo','Templo de San Cristóbal'], en:['Sumidero Canyon by boat','Santo Domingo market','San Cristóbal temple'] },
      diasRecomendados:3, imagenesHotel:['https://picsum.photos/seed/chiapas-eco-1/800/600','https://picsum.photos/seed/chiapas-eco-2/800/600','https://picsum.photos/seed/chiapas-eco-3/800/600'] },
    { nivel:'medio', color:'#e9c46a', emoji:'★', precioTotal:'$5,800 MXN', hotel:'Hotel Casa Mexicana', estrellas:3, precioHotel:'$980 MXN / noche',
      descripcionHotel:{ es:'Hotel boutique colonial en el corazón de San Cristóbal, con jardín interior y spa.', en:'Colonial boutique hotel in the heart of San Cristóbal, with interior garden and spa.' },
      incluye:{ es:['WiFi gratuito','Desayuno buffet','Piscina','Estacionamiento'], en:['Free WiFi','Buffet breakfast','Pool','Parking'] },
      restaurante:'TierrAdentro', tipoCocina:{ es:'Fusión mexicana contemporánea', en:'Contemporary Mexican fusion' }, precioRestaurante:'$380 MXN por persona',
      platillo:{ es:'Cochinita pibil con achiote y habanero', en:'Cochinita pibil with achiote and habanero' },
      transporte:{ es:'Taxi privado + tours organizados', en:'Private taxi + organized tours' }, precioTransporte:'$250 MXN / día',
      actividades:{ es:['Tour Cascadas de Agua Azul','Palenque ruinas mayas','Pueblo mágico Zinacantán'], en:['Agua Azul Waterfalls tour','Palenque Mayan ruins','Zinacantán magic town'] },
      diasRecomendados:4, imagenesHotel:['https://picsum.photos/seed/chiapas-med-1/800/600','https://picsum.photos/seed/chiapas-med-2/800/600','https://picsum.photos/seed/chiapas-med-3/800/600'] },
    { nivel:'premium', color:'#DD331D', emoji:'◆', precioTotal:'$12,000 MXN', hotel:'Na Bolom Lodge', estrellas:5, precioHotel:'$2,800 MXN / noche',
      descripcionHotel:{ es:'Lodge de lujo ecológico rodeado de selva lacandona, con guías especializados en cultura maya.', en:'Eco-luxury lodge surrounded by Lacandon jungle, with expert Mayan culture guides.' },
      incluye:{ es:['Todo incluido','Spa completo','Tours privados','Traslados en camioneta privada','Guía bilingüe'], en:['All inclusive','Full spa','Private tours','Private van transfers','Bilingual guide'] },
      restaurante:'La Viña de Bacco', tipoCocina:{ es:'Alta cocina mexicana', en:'High-end Mexican cuisine' }, precioRestaurante:'$900 MXN por persona',
      platillo:{ es:'Filete de res con reducción de mezcal y mole negro', en:'Beef tenderloin with mezcal reduction and black mole' },
      transporte:{ es:'Camioneta privada 4x4', en:'Private 4x4 van' }, precioTransporte:'Incluido en paquete',
      actividades:{ es:['Vuelo en helicóptero sobre Cañón del Sumidero','Tour privado Palenque al amanecer','Ceremonia tzeltal con chamán local','Snorkel en Lagos de Montebello'], en:['Helicopter flight over Sumidero Canyon','Private Palenque tour at dawn','Tzeltal ceremony with local shaman','Snorkeling at Montebello Lakes'] },
      diasRecomendados:5, imagenesHotel:['https://picsum.photos/seed/chiapas-pre-1/800/600','https://picsum.photos/seed/chiapas-pre-2/800/600','https://picsum.photos/seed/chiapas-pre-3/800/600'] },
  ],
  'Yucatán': [
    { nivel:'economico', color:'#3AB7A5', emoji:'$', precioTotal:'$2,800 MXN', hotel:'Hostal Nomadas', estrellas:2, precioHotel:'$320 MXN / noche',
      descripcionHotel:{ es:'Hostal céntrico en Mérida, a dos cuadras del Zócalo. Ambiente joven y viajero.', en:'Central hostel in Mérida, two blocks from the Zócalo. Young traveler atmosphere.' },
      incluye:{ es:['WiFi gratuito','Cocina compartida','Bicicletas de préstamo'], en:['Free WiFi','Shared kitchen','Loan bicycles'] },
      restaurante:'La Chaya Maya', tipoCocina:{ es:'Comida yucateca auténtica', en:'Authentic Yucatan cuisine' }, precioRestaurante:'$150 MXN por persona',
      platillo:{ es:'Sopa de lima y panuchos con cochinita', en:'Lime soup and panuchos with cochinita' },
      transporte:{ es:'Bicicleta + ADO bus', en:'Bicycle + ADO bus' }, precioTransporte:'$100 MXN / día',
      actividades:{ es:['Chichén Itzá (entrada general)','Cenote Ik Kil','Paseo en calesa por Mérida'], en:['Chichén Itzá (general admission)','Ik Kil cenote','Horse-drawn carriage ride in Mérida'] },
      diasRecomendados:3, imagenesHotel:['https://picsum.photos/seed/yucatan-eco-1/800/600','https://picsum.photos/seed/yucatan-eco-2/800/600','https://picsum.photos/seed/yucatan-eco-3/800/600'] },
    { nivel:'medio', color:'#e9c46a', emoji:'★', precioTotal:'$6,500 MXN', hotel:'Hacienda Xcanatún', estrellas:4, precioHotel:'$1,400 MXN / noche',
      descripcionHotel:{ es:'Hacienda henequenera del siglo XVIII restaurada, con piscina de aguas termales y spa.', en:'Restored 18th-century henequen hacienda with thermal pool and spa.' },
      incluye:{ es:['Desayuno gourmet','Piscina','Spa','WiFi','Traslado aeropuerto'], en:['Gourmet breakfast','Pool','Spa','WiFi','Airport transfer'] },
      restaurante:'Casa de Piedra', tipoCocina:{ es:'Nouvelle cuisine yucateca', en:'Nouvelle Yucatan cuisine' }, precioRestaurante:'$550 MXN por persona',
      platillo:{ es:'Poc Chuc con ensalada de jícama y naranja', en:'Poc Chuc with jicama and orange salad' },
      transporte:{ es:'Auto rentado + guía turístico', en:'Rental car + tour guide' }, precioTransporte:'$400 MXN / día',
      actividades:{ es:['Tour privado Chichén Itzá + Uxmal','Nado en cenotes privados','Mercado Lucas de Gálvez con chef local'], en:['Private Chichén Itzá + Uxmal tour','Swimming in private cenotes','Lucas de Gálvez market with local chef'] },
      diasRecomendados:4, imagenesHotel:['https://picsum.photos/seed/yucatan-med-1/800/600','https://picsum.photos/seed/yucatan-med-2/800/600','https://picsum.photos/seed/yucatan-med-3/800/600'] },
    { nivel:'premium', color:'#DD331D', emoji:'◆', precioTotal:'$15,000 MXN', hotel:'Chablé Resort & Spa', estrellas:5, precioHotel:'$4,500 MXN / noche',
      descripcionHotel:{ es:'Resort de ultra lujo con cenote privado, villas con piscina individual y conexión espiritual maya.', en:'Ultra-luxury resort with private cenote, villas with individual pool and Mayan spiritual connection.' },
      incluye:{ es:['Todo incluido premium','Cenote privado','Piscina privada en villa','Butler 24h','Helipuerto','Tours exclusivos'], en:['Premium all inclusive','Private cenote','Private villa pool','24h butler','Helipad','Exclusive tours'] },
      restaurante:"Ixi'im Restaurant", tipoCocina:{ es:'Alta cocina maya contemporánea', en:'High-end contemporary Mayan cuisine' }, precioRestaurante:'$1,800 MXN por persona',
      platillo:{ es:'Venado con pepita negra, hierba santa y trufa blanca', en:'Venison with black pepita, holy herb and white truffle' },
      transporte:{ es:'Helicóptero o SUV privado', en:'Helicopter or private SUV' }, precioTransporte:'Incluido en paquete',
      actividades:{ es:['Acceso privado nocturno a Chichén Itzá','Experiencia espiritual con sacerdote maya','Yate privado por la costa yucateca','Clase de cocina con chef Michelín'], en:['Private night access to Chichén Itzá','Spiritual experience with Mayan priest','Private yacht along the Yucatan coast','Cooking class with Michelin chef'] },
      diasRecomendados:6, imagenesHotel:['https://picsum.photos/seed/yucatan-pre-1/800/600','https://picsum.photos/seed/yucatan-pre-2/800/600','https://picsum.photos/seed/yucatan-pre-3/800/600'] },
  ],
  'default': [
    { nivel:'economico', color:'#3AB7A5', emoji:'$', precioTotal:'$2,200 MXN', hotel:'Hostal del Viajero', estrellas:2, precioHotel:'$300 MXN / noche',
      descripcionHotel:{ es:'Hostal céntrico con ambiente familiar, ideal para mochileros y viajeros independientes.', en:'Central hostel with a family atmosphere, ideal for backpackers and independent travelers.' },
      incluye:{ es:['WiFi gratuito','Cocina compartida','Casilleros seguros'], en:['Free WiFi','Shared kitchen','Secure lockers'] },
      restaurante:'Fonda La Tradicional', tipoCocina:{ es:'Comida mexicana casera', en:'Traditional homestyle Mexican cuisine' }, precioRestaurante:'$100 MXN por persona',
      platillo:{ es:'Comida corrida con sopa, guisado y postre', en:'Set lunch with soup, stew and dessert' },
      transporte:{ es:'Transporte público local', en:'Local public transport' }, precioTransporte:'$60 MXN / día',
      actividades:{ es:['Visita al centro histórico','Mercado local','Parque principal'], en:['Historic center visit','Local market','Main park'] },
      diasRecomendados:2, imagenesHotel:['https://picsum.photos/seed/default-eco-1/800/600','https://picsum.photos/seed/default-eco-2/800/600','https://picsum.photos/seed/default-eco-3/800/600'] },
    { nivel:'medio', color:'#e9c46a', emoji:'★', precioTotal:'$5,500 MXN', hotel:'Hotel Boutique Local', estrellas:3, precioHotel:'$900 MXN / noche',
      descripcionHotel:{ es:'Hotel boutique de estilo regional con decoración artesanal y excelente ubicación.', en:'Regional-style boutique hotel with artisan décor and excellent location.' },
      incluye:{ es:['Desayuno incluido','WiFi','Piscina','Estacionamiento'], en:['Breakfast included','WiFi','Pool','Parking'] },
      restaurante:'Restaurante del Centro', tipoCocina:{ es:'Cocina regional mexicana', en:'Regional Mexican cuisine' }, precioRestaurante:'$350 MXN por persona',
      platillo:{ es:'Especialidad regional de temporada', en:'Seasonal regional specialty' },
      transporte:{ es:'Taxi + tours organizados', en:'Taxi + organized tours' }, precioTransporte:'$220 MXN / día',
      actividades:{ es:['Tour guiado por el centro','Visita a zonas arqueológicas cercanas','Taller artesanal local'], en:['Guided downtown tour','Visit to nearby archaeological sites','Local craft workshop'] },
      diasRecomendados:3, imagenesHotel:['https://picsum.photos/seed/default-med-1/800/600','https://picsum.photos/seed/default-med-2/800/600','https://picsum.photos/seed/default-med-3/800/600'] },
    { nivel:'premium', color:'#DD331D', emoji:'◆', precioTotal:'$11,000 MXN', hotel:'Gran Hotel de Lujo', estrellas:5, precioHotel:'$2,500 MXN / noche',
      descripcionHotel:{ es:'Hotel cinco estrellas con spa, restaurante gourmet y servicio de concierge personalizado.', en:'Five-star hotel with spa, gourmet restaurant and personalized concierge service.' },
      incluye:{ es:['Todo incluido','Spa completo','Traslados privados','Guía bilingüe exclusivo','Tours privados'], en:['All inclusive','Full spa','Private transfers','Exclusive bilingual guide','Private tours'] },
      restaurante:'Alta Cocina Regional', tipoCocina:{ es:'Gastronomía de autor', en:'Signature gastronomy' }, precioRestaurante:'$1,200 MXN por persona',
      platillo:{ es:'Menú degustación de 7 tiempos con maridaje', en:'7-course tasting menu with wine pairing' },
      transporte:{ es:'Vehículo privado con chofer', en:'Private vehicle with driver' }, precioTransporte:'Incluido en paquete',
      actividades:{ es:['Tours privados a sitios exclusivos','Experiencia cultural personalizada','Cena de gala en locación histórica','Traslado en helicóptero opcional'], en:['Private tours to exclusive sites','Personalized cultural experience','Gala dinner at historic venue','Optional helicopter transfer'] },
      diasRecomendados:5, imagenesHotel:['https://picsum.photos/seed/default-pre-1/800/600','https://picsum.photos/seed/default-pre-2/800/600','https://picsum.photos/seed/default-pre-3/800/600'] },
  ],
};