module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/dist/',
    '<rootDir>/.claude/',
    '<rootDir>/.claire/',
    '<rootDir>/.kilo/',
    '<rootDir>/e2e/',
  ],
  modulePathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/.claude/',
    '<rootDir>/.claire/',
    '<rootDir>/.kilo/',
  ],
  watchPathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/.claude/',
    '<rootDir>/.claire/',
    '<rootDir>/.kilo/',
  ],
  collectCoverageFrom: [
    'lib/**/*.{ts,tsx}',
    'app/**/*.{ts,tsx}',
    'components/**/*.{ts,tsx}',
    'hooks/**/*.{ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/.expo/**',
    '!**/coverage/**',
    '!**/dist/**',
    '!**/.claude/**',
    '!**/.claire/**',
    '!**/.kilo/**',
    '!**/e2e/**',
    '!**/scripts/**',
    '!**/android/**',
    '!**/ios/**',
  ],
  coverageThresholds: {
    global: {
      branches: 50,
      functions: 50,
      lines: 50,
      statements: 50,
    },
    './lib/supabase-db.ts': { lines: 70 },
    './lib/offline-cache.ts': { lines: 70 },
    './lib/sync-user-data.ts': { lines: 60 },
  },
  testMatch: [
    '**/__tests__/**/*.(ts|tsx|js)',
    '**/?(*.)+(spec|test).(ts|tsx|js)',
  ],
  coverageReporters: ['lcov', 'text', 'text-summary'],
};
