server {
    listen PORT_PLACEHOLDER;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        log_not_found off;
    }

    location ~* \.(ttf|woff|woff2|otf|eot)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Access-Control-Allow-Origin *;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
