import { Platform, StatusBar, StyleSheet } from 'react-native';
import { sombra } from './estilos';
import { Tema } from './tema';

export const s = StyleSheet.create({
  contenedor:          { flex: 1, backgroundColor: '#FAF7F0' },
  imagenMapa:          { opacity: 0.1, position: 'absolute', width: '90%', height: '100%', alignSelf: 'center' },
  logoFijo:            { position: 'absolute', top: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 24) + 4 : 12, left: 12, width: 50, height: 50, zIndex: 10 },
  layoutPC:            { flex: 1, flexDirection: 'row' },
  layoutMovil:         { flex: 1, flexDirection: 'column' },
  areaSegura:          { flex: 1 },
  areaSeguraPC:        { flex: 1 },

  sidebar:             { width: 64, backgroundColor: '#fff', borderRightWidth: 1, borderRightColor: '#e8e8e8', alignItems: 'center', paddingTop: 16, paddingBottom: 20, gap: 4 },
  logoSidebar:         { width: 48, height: 48, marginBottom: 6 },
  separadorSidebar:    { width: 40, height: 1, backgroundColor: '#eee', marginVertical: 12 },
  itemSidebar:         { width: 56, height: 56, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  itemSidebarActivo:   { backgroundColor: '#f0faf9' },
  iconoSidebar:        { width: 28, height: 28 },

  envolturaBarra:      { width: '100%', backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#e0e0e0', paddingBottom: Platform.OS === 'android' ? 16 : 8 },
  barraPestanas:       { flexDirection: 'row', backgroundColor: '#fff', width: '100%', maxWidth: 800, alignSelf: 'center' },
  itemPestana:         { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 8, height: 56 },
  etiquetaPestana:     { fontSize: 10, color: '#999', marginTop: 2 },
  etiquetaPestanaActiva:{ color: Tema.primario, fontWeight: '600' },

  encabezado:          { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8, width: '100%', maxWidth: 800, alignSelf: 'center' },
  botonAtras:          { width: 38, height: 38, borderRadius: 19, backgroundColor: '#F0F0F0', alignItems: 'center', justifyContent: 'center' },
  textoAtras:          { fontSize: 26, color: Tema.primario, lineHeight: 30 },
  tituloEncabezado:    { flex: 1, fontSize: 17, fontWeight: '800', color: '#222', textAlign: 'center' },

  heroBox: {
    marginHorizontal: 16,
    marginTop: 60,
    marginBottom: 20,
    backgroundColor: Tema.primario,
    borderRadius: 24,
    padding: 22,
    ...sombra({ color: Tema.primario, opacity: 0.3, radius: 14, offsetY: 6, elevation: 6 }),
  },
  heroTitulo:          { fontSize: 26, fontWeight: '900', color: '#fff', marginBottom: 6 },
  heroSub:             { fontSize: 13, color: 'rgba(255,255,255,0.85)', lineHeight: 19, marginBottom: 18 },
  heroBtnNuevo:        { backgroundColor: '#fff', borderRadius: 14, paddingVertical: 12, alignItems: 'center' },
  heroBtnTxt:          { color: Tema.primarioOscuro, fontSize: 15, fontWeight: '800' },

  contenedorScroll:    { paddingBottom: 30, width: '100%', maxWidth: 800, alignSelf: 'center' },

  seccionHead:         { paddingHorizontal: 16, marginBottom: 12 },
  seccionTitulo:       { fontSize: 18, fontWeight: '800', color: '#222' },
  seccionSub:          { fontSize: 12, color: '#888', marginTop: 2 },

  scrollHorizontal:    { paddingHorizontal: 16, paddingBottom: 4, gap: 14 },
  itiCard: {
    width: 190,
    backgroundColor: '#fff',
    borderRadius: 18,
    overflow: 'hidden',
    borderTopWidth: 4,
    ...sombra({ opacity: 0.1, radius: 8, offsetY: 3, elevation: 4 }),
  },
  itiStrip:            { height: 0 },
  itiCardBody:         { padding: 14 },
  itiNombre:           { fontSize: 15, fontWeight: '800', color: '#222', marginBottom: 4 },
  itiCount:            { fontSize: 12, color: '#888', marginBottom: 12 },
  itiImgsRow:          { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  itiMiniImg:          { width: 36, height: 36, borderRadius: 18, borderWidth: 2, borderColor: '#fff' },
  itiVacioTxt:         { fontSize: 11, color: '#bbb' },
  itiChevron:          { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10, alignSelf: 'flex-start' },
  itiChevronTxt:       { fontSize: 12, fontWeight: '700' },

  vacioPrincipal:      { marginHorizontal: 16, marginTop: 4, marginBottom: 20, padding: 26, backgroundColor: '#fff', borderRadius: 18, alignItems: 'center', borderWidth: 1.5, borderColor: '#eee', borderStyle: 'dashed' },
  tituloVacioP:        { fontSize: 17, fontWeight: '800', color: '#333', marginBottom: 6 },
  subVacioP:           { fontSize: 13, color: '#888', textAlign: 'center', lineHeight: 20 },

  divisor:             { height: 1, backgroundColor: '#E8E8E8', marginVertical: 22, marginHorizontal: 20 },

  gridSugeridas:       { paddingHorizontal: 14, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  tarjetaSug: {
    borderRadius: 18,
    overflow: 'hidden',
    height: 200,
    backgroundColor: '#ddd',
    ...sombra({ opacity: 0.1, radius: 8, offsetY: 4, elevation: 4 }),
  },
  imgSug:              { width: '100%', height: '100%', position: 'absolute' },
  gradienteSug:        { position: 'absolute', bottom: 0, left: 0, right: 0, height: 100, backgroundColor: 'rgba(0,0,0,0.45)' },
  badgeNivel:          { position: 'absolute', top: 12, left: 12, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  badgeNivelTxt:       { color: '#fff', fontSize: 11, fontWeight: '700' },
  infoSug:             { position: 'absolute', bottom: 14, left: 14 },
  tituloSug:           { fontSize: 20, fontWeight: '900', color: '#fff' },
  estadoSug:           { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 2 },

  statsBanner: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    ...sombra({ opacity: 0.08, radius: 6, offsetY: 2, elevation: 2 }),
  },
  statChip:            { alignItems: 'center', flex: 1 },
  statEmoji:           { fontSize: 18, marginBottom: 2 },
  statLabel:           { fontSize: 11, fontWeight: '700', color: '#333', textAlign: 'center' },
  statDivisor:         { width: 1, height: 32, backgroundColor: '#eee' },

  accionesBarra:       { flexDirection: 'row', gap: 10, marginHorizontal: 16, marginBottom: 14 },
  accionBtn:           { flex: 1, backgroundColor: '#EEF8F7', paddingVertical: 10, borderRadius: 12, alignItems: 'center' },
  accionBtnDanger:     { backgroundColor: '#FEF0EE' },
  accionBtnTxt:        { fontSize: 13, fontWeight: '700', color: Tema.primarioOscuro },

  listaItems:          { paddingHorizontal: 16, paddingTop: 4, paddingBottom: 40 },
  tarjetaItem:         { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 14, position: 'relative' },
  lineaTimeline:       { position: 'absolute', left: 18, top: 38, width: 2, height: 40, backgroundColor: '#E0E0E0', zIndex: 0 },
  burbujaPaso: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#fff',
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    zIndex: 1,
    ...sombra({ opacity: 0.1, radius: 4, offsetY: 2, elevation: 2 }),
  },
  textoBurbuja:        { fontSize: 13, fontWeight: '900' },
  cuerpoItem: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    ...sombra({ opacity: 0.08, radius: 6, offsetY: 2, elevation: 3 }),
  },
  imgItem:             { width: 72, height: 80 },
  infoItem:            { flex: 1, padding: 10, justifyContent: 'center' },
  tituloItem:          { fontSize: 14, fontWeight: '800', color: '#222', marginBottom: 2 },
  estadoItem:          { fontSize: 11, color: '#888', marginBottom: 6 },
  chipNivel:           { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8 },
  chipNivelTxt:        { fontSize: 10, fontWeight: '800' },
  controlesItem:       { padding: 8, alignItems: 'center', justifyContent: 'center', gap: 6 },
  btnMover:            { width: 28, height: 28, borderRadius: 8, backgroundColor: '#F5F5F5', alignItems: 'center', justifyContent: 'center' },
  btnMoverTxt:         { fontSize: 16, color: '#555', lineHeight: 22 },
  btnEliminar:         { width: 28, height: 28, borderRadius: 8, backgroundColor: '#FEF0EE', alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  btnEliminarTxt:      { fontSize: 12, color: Tema.acento, fontWeight: '900' },

  vacio:               { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
  textoVacioEmoji:     { fontSize: 56, marginBottom: 14 },
  tituloVacio:         { fontSize: 20, fontWeight: '900', color: '#333', marginBottom: 8 },
  subtituloVacio:      { fontSize: 14, color: '#888', textAlign: 'center', lineHeight: 21 },

  modalOverlay:        { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  modalBox:            { backgroundColor: '#fff', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 28, paddingBottom: 40 },
  modalHandle:         { width: 40, height: 4, borderRadius: 2, backgroundColor: '#DDD', alignSelf: 'center', marginBottom: 20 },
  modalTitulo:         { fontSize: 22, fontWeight: '900', color: '#222', marginBottom: 4 },
  modalSub:            { fontSize: 14, color: '#888', marginBottom: 20 },
  modalInput:          { backgroundColor: '#F5F5F5', borderRadius: 14, padding: 16, fontSize: 16, color: '#333', borderWidth: 1.5, borderColor: '#E8E8E8', marginBottom: 20 },
  modalBtns:           { flexDirection: 'row', gap: 12 },
  modalBtnCancelar:    { flex: 1, paddingVertical: 14, borderRadius: 14, alignItems: 'center', borderWidth: 1.5, borderColor: '#E8E8E8' },
  modalBtnCancelarTxt: { fontSize: 15, fontWeight: '700', color: '#666' },
  modalBtnCrear:       { flex: 1, paddingVertical: 14, borderRadius: 14, alignItems: 'center', backgroundColor: Tema.primarioOscuro },
  modalBtnCrearTxt:    { fontSize: 15, fontWeight: '800', color: '#fff' },

  modalImgHeader:      { width: '100%', height: 150, borderRadius: 16, marginBottom: 12 },
  modalCarousel:       { width: '100%', marginBottom: 12 },
  modalNivelBadge:     { position: 'absolute', top: 44, right: 24, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  modalNivelTxt:       { color: '#fff', fontSize: 11, fontWeight: '800' },
  modalEstado:         { fontSize: 13, color: '#888', marginBottom: 10 },
  modalResumenFila:    { flexDirection: 'row', gap: 10, marginBottom: 10 },
  modalResumenCard:    { flex: 1, backgroundColor: '#F8F8F8', borderRadius: 12, padding: 12 },
  modalResumenEyebrow: { fontSize: 11, color: '#888', fontWeight: '700', marginBottom: 4 },
  modalResumenValor:   { fontSize: 14, color: '#222', fontWeight: '800' },
  modalTagRow:         { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 14 },
  modalTag:            { backgroundColor: '#F0F0F0', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  modalTagTxt:         { fontSize: 11, color: '#555', fontWeight: '600' },
  modalSeccion:        { backgroundColor: '#F8F8F8', borderRadius: 12, padding: 12, marginBottom: 10 },
  modalSeccionTitulo:  { fontSize: 12, color: '#888', fontWeight: '700', marginBottom: 4 },
  modalSeccionVal:     { fontSize: 15, fontWeight: '800', color: '#222', marginBottom: 2 },
  modalSeccionSub:     { fontSize: 12, color: Tema.primarioOscuro, fontWeight: '600' },
  modalSeccionBody:    { fontSize: 13, color: '#666', lineHeight: 19, marginTop: 6 },
  modalMiniChips:      { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  modalMiniChip:       { backgroundColor: '#EEF8F7', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  modalMiniChipTxt:    { fontSize: 11, color: Tema.primarioOscuro, fontWeight: '700' },
  modalActividad:      { fontSize: 13, color: '#555', lineHeight: 20, marginTop: 4 },
  modalBtnAgregar:     { backgroundColor: Tema.primarioOscuro, borderRadius: 14, paddingVertical: 14, alignItems: 'center', marginTop: 14 },
  modalBtnAgregarTxt:  { color: '#fff', fontSize: 15, fontWeight: '800' },

  itiOpcion:           { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#F0F0F0' },
  itiOpcionNombre:     { fontSize: 15, fontWeight: '700', color: '#222' },
  itiOpcionCount:      { fontSize: 12, color: '#888' },
  oCrearLbl:           { textAlign: 'center', fontSize: 12, color: '#aaa', marginVertical: 10 },

  tapHint:             { marginTop: 6, backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, alignSelf: 'flex-start' },
  tapHintTxt:          { color: '#fff', fontSize: 11, fontWeight: '700' },

  // ── Estilos para tarjetas de rutas (igual que estados) ──
  tarjetaContenedor:   { position: 'relative', marginBottom: 14 },
  tarjeta:             {
    borderRadius: 16,
    overflow: 'hidden',
    height: 180,
    backgroundColor: '#ddd',
    borderWidth: 2,
    borderColor: Tema.primario,
    ...sombra({ opacity: 0.1, radius: 8, offsetY: 4, elevation: 4 }),
  },
  imagenTarjeta:       { width: '100%', height: '100%', position: 'absolute' },
  sombraOverlay:       { position: 'absolute', bottom: 0, left: 0, right: 0, height: 80, backgroundColor: 'rgba(0,0,0,0.35)' },
  badgeCategoria:      { position: 'absolute', top: 10, left: 10, backgroundColor: 'rgba(46,154,138,0.92)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  textoBadge:          { color: '#fff', fontSize: 11, fontWeight: '700' },
  nombreTarjeta:       { position: 'absolute', bottom: 28, left: 14, fontSize: 20, fontWeight: '700', color: '#fff' },
  precioTarjeta:       { position: 'absolute', bottom: 10, left: 14, fontSize: 12, color: '#ffffffcc' },
  botonFavorito:       {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    ...sombra({ opacity: 0.15, radius: 4, offsetY: 2, elevation: 3 }),
  },
});
