export type Idioma = 'es' | 'en';

type Traducible = { [key in Idioma]: string };

const T: Record<string, Traducible> = {
  // ── Pestañas de navegación ─────────────────────────────────
  tab_menu:        { es: 'Inicio',      en: 'Home'        },
  tab_favoritos:   { es: 'Favoritos',   en: 'Favorites'   },
  tab_rutas:       { es: 'Rutas',       en: 'Routes'      },
  tab_perfil:      { es: 'Perfil',      en: 'Profile'     },

  // ── Menu / Pantalla principal ──────────────────────────────
  menu_saludo:          { es: 'Hola, {nombre}',              en: 'Hi, {nombre}'               },
  menu_subtitulo:       { es: 'Descubre México',             en: 'Discover Mexico'            },
  menu_buscar:          { es: 'Buscar destino...',           en: 'Search destination...'      },
  menu_orden_az:        { es: 'Orden A-Z',                   en: 'A-Z Order'                  },
  menu_menor_precio:    { es: 'Menor precio',                en: 'Lowest price'               },
  menu_mayor_precio:    { es: 'Mayor precio',                en: 'Highest price'              },
  menu_cargando:        { es: 'Cargando destinos...',        en: 'Loading destinations...'    },
  menu_sin_resultados:  { es: 'Sin resultados',              en: 'No results'                 },
  menu_sin_resultados2: { es: 'Intenta con otra búsqueda o categoría', en: 'Try a different search or category' },
  menu_limpiar:         { es: 'Limpiar filtros',             en: 'Clear filters'              },
  menu_precio_desde:    { es: 'Desde ${precio} MXN',         en: 'From ${precio} MXN'         },
  menu_cat_todos:       { es: 'Todos',                       en: 'All'                        },
  menu_cat_playa:       { es: 'Playa',                       en: 'Beach'                      },
  menu_cat_cultura:     { es: 'Cultura',                     en: 'Culture'                    },
  menu_cat_aventura:    { es: 'Aventura',                    en: 'Adventure'                  },
  menu_cat_gastro:      { es: 'Gastronomía',                 en: 'Gastronomy'                 },
  menu_cat_ciudad:      { es: 'Ciudad',                      en: 'City'                       },
  menu_destino_singular:{ es: 'destino encontrado',          en: 'destination found'          },
  menu_destino_plural:  { es: 'destinos encontrados',        en: 'destinations found'         },

  // ── Favoritos ──────────────────────────────────────────────
  fav_titulo:         { es: 'Mis favoritos',                  en: 'My favorites'               },
  fav_cargando:       { es: 'Cargando favoritos...',          en: 'Loading favorites...'       },
  fav_vacios:         { es: 'Sin favoritos aún',              en: 'No favorites yet'           },
  fav_vacios2:        { es: 'Agrega destinos desde el menú principal', en: 'Add destinations from the main menu' },
  fav_explorar:       { es: 'Explorar destinos',              en: 'Explore destinations'       },
  fav_precio_desde:   { es: 'Desde ${precio} MXN',            en: 'From ${precio} MXN'         },

  // ── Historial ──────────────────────────────────────────────
  hist_titulo:        { es: 'Historial',                      en: 'History'                    },
  hist_ahora:         { es: 'Justo ahora',                    en: 'Just now'                   },
  hist_hace_min:      { es: 'Hace {n} min',                   en: '{n} min ago'                },
  hist_hace_h:        { es: 'Hace {n}h',                      en: '{n}h ago'                   },
  hist_hace_d:        { es: 'Hace {n}d',                      en: '{n}d ago'                   },
  hist_evento_singular:{ es: 'evento',                        en: 'event'                      },
  hist_evento_plural: { es: 'eventos',                        en: 'events'                     },
  hist_cargar_mas:    { es: 'Cargar más eventos',             en: 'Load more events'           },
  hist_vacio:         { es: 'Sin actividad',                  en: 'No activity'                },
  hist_vacio2:        { es: 'Tu historial aparecerá aquí',    en: 'Your history will appear here' },

  // ── Notificaciones ────────────────────────────────────────
  notif_titulo:       { es: 'Notificaciones',                 en: 'Notifications'              },
  notif_ahora:        { es: 'Ahora mismo',                    en: 'Just now'                   },
  notif_hace_min:     { es: 'Hace {n} min',                   en: '{n} min ago'                },
  notif_hace_h_s:     { es: 'Hace {n} hora',                  en: '{n} hour ago'               },
  notif_hace_h_p:     { es: 'Hace {n} horas',                 en: '{n} hours ago'              },
  notif_ayer:         { es: 'Ayer',                           en: 'Yesterday'                  },
  notif_hace_d:       { es: 'Hace {n} días',                  en: '{n} days ago'               },
  notif_sin_leer:     { es: '{n} sin leer',                   en: '{n} unread'                 },
  notif_todas:        { es: 'Todas',                          en: 'All'                        },
  notif_no_leidas:    { es: 'Sin leer',                       en: 'Unread'                     },
  notif_marcar_todas: { es: 'Marcar todas',                   en: 'Mark all'                   },
  notif_vacio:        { es: 'Sin notificaciones',             en: 'No notifications'           },
  notif_vacio_sub:    { es: 'No tienes notificaciones aún',   en: 'No notifications yet'       },
  notif_leidas_sub:   { es: 'Todas están leídas',             en: 'All caught up'              },
  notif_cargar_mas:   { es: 'Cargar más notificaciones',      en: 'Load more notifications'    },

  // ── Mis reservas ───────────────────────────────────────────
  res_titulo:         { es: 'Mis reservas',                   en: 'My bookings'                },
  res_todas:          { es: 'Todas',                          en: 'All'                        },
  res_confirmadas:    { es: 'Confirmadas',                    en: 'Confirmed'                  },
  res_pendientes:     { es: 'Pendientes',                     en: 'Pending'                    },
  res_completadas:    { es: 'Completadas',                    en: 'Completed'                  },
  res_canceladas:     { es: 'Canceladas',                     en: 'Cancelled'                  },
  res_estado_confirmada: { es: '✓ Confirmada',               en: '✓ Confirmed'                },
  res_estado_pendiente:  { es: '⏳ Pendiente',               en: '⏳ Pending'                 },
  res_estado_completada: { es: '✔ Completada',               en: '✔ Completed'               },
  res_estado_cancelada:  { es: '✕ Cancelada',                en: '✕ Cancelled'               },
  res_total_singular: { es: 'reserva en total',               en: 'booking total'              },
  res_total_plural:   { es: 'reservas en total',              en: 'bookings total'             },
  res_vacias:         { es: 'Sin reservas',                   en: 'No bookings'                },
  res_vacias2:        { es: 'Aquí aparecerán tus reservas',   en: 'Your bookings will appear here' },
  res_sin_resultado:  { es: 'Sin resultados',                 en: 'No results'                 },
  res_sin_resultado2: { es: 'No tienes reservas en esta categoría', en: 'No bookings in this category' },
  res_folio:          { es: 'Folio',                          en: 'Ref.'                       },
  res_fecha:          { es: 'Fecha',                          en: 'Date'                       },
  res_personas:       { es: 'Personas',                       en: 'People'                     },
  res_total:          { es: 'Total',                          en: 'Total'                      },
  res_paquete:        { es: 'Paquete {n}',                    en: 'Package {n}'                },
  res_cancelar_msg:   { es: '¿Cancelar la reserva {folio}? Esta acción no se puede deshacer.', en: 'Cancel booking {folio}? This action cannot be undone.' },
  res_cancelar_no:    { es: 'No, mantener',                   en: 'No, keep it'                },
  res_cancelar_si:    { es: 'Sí, cancelar',                   en: 'Yes, cancel'                },
  res_ver_destino:    { es: 'Ver destino →',                  en: 'View destination →'         },
  res_btn_cancelar:   { es: '✕ Cancelar',                     en: '✕ Cancel'                   },
  res_btn_reservar:   { es: '↺ Volver a reservar',            en: '↺ Book again'               },
  res_notas:          { es: 'Notas del viajero',               en: 'Traveler notes'             },
  res_cargar_mas:     { es: 'Cargar más reservas',             en: 'Load more bookings'         },
  res_vacio:          { es: 'Sin reservas',                    en: 'No bookings'                },

  // ── Reserva (flujo paso 1) ─────────────────────────────────
  rsv_paso_reserva:     { es: 'Reserva',                      en: 'Booking'                    },
  rsv_paso_pago:        { es: 'Pago',                         en: 'Payment'                    },
  rsv_paso_confirmacion:{ es: 'Confirmación',                 en: 'Confirmation'               },
  rsv_datos_viaje:      { es: 'Datos del viaje',              en: 'Trip details'               },
  rsv_paquete:          { es: 'Paquete {n}',                  en: 'Package {n}'                },
  rsv_resumen:          { es: 'Resumen de tu selección',      en: 'Your selection summary'     },
  rsv_destino:          { es: 'Destino',                      en: 'Destination'                },
  rsv_precio_persona:   { es: 'Precio por persona',           en: 'Price per person'           },
  rsv_num_personas:     { es: 'Número de personas',           en: 'Number of people'           },
  rsv_total:            { es: 'Total',                        en: 'Total'                      },
  rsv_nombre:           { es: 'Nombre completo',              en: 'Full name'                  },
  rsv_correo:           { es: 'Correo electrónico',           en: 'Email address'              },
  rsv_telefono:         { es: 'Teléfono',                     en: 'Phone'                      },
  rsv_fecha:            { es: 'Fecha de viaje (DD/MM/AAAA)',  en: 'Travel date (DD/MM/YYYY)'   },
  rsv_notas:            { es: 'Notas adicionales (opcional)', en: 'Additional notes (optional)'},
  rsv_notas_hint:       { es: 'Alergias, preferencias especiales, etc.', en: 'Allergies, special preferences, etc.' },
  rsv_continuar:        { es: 'Continuar al pago →',          en: 'Continue to payment →'     },
  rsv_err_nombre:       { es: 'Ingresa tu nombre completo',   en: 'Enter your full name'       },
  rsv_err_correo:       { es: 'Ingresa un correo válido',     en: 'Enter a valid email'        },
  rsv_err_telefono:     { es: 'Ingresa tu teléfono',          en: 'Enter your phone'           },
  rsv_err_fecha:        { es: 'Ingresa la fecha de viaje',    en: 'Enter the travel date'      },
  rsv_ph_nombre:        { es: 'Juan Pérez',                   en: 'John Doe'                   },
  rsv_ph_correo:        { es: 'juan@correo.com',              en: 'john@email.com'             },
  rsv_ph_telefono:      { es: '55 1234 5678',                 en: '555 123 4567'               },
  rsv_ph_fecha:         { es: '15/08/2025',                   en: '08/15/2025'                 },

  // ── Pago ───────────────────────────────────────────────────
  pago_titulo:          { es: 'Método de pago',               en: 'Payment method'             },
  pago_total:           { es: 'Total a pagar',                en: 'Total to pay'               },
  pago_destino:         { es: 'Destino',                      en: 'Destination'                },
  pago_personas:        { es: 'Personas',                     en: 'People'                     },
  pago_fecha:           { es: 'Fecha',                        en: 'Date'                       },
  pago_selecciona:      { es: 'Selecciona tu método',         en: 'Select your method'         },
  pago_tarjeta:         { es: 'Tarjeta',                      en: 'Card'                       },
  pago_credito_debito:  { es: 'Crédito o débito',             en: 'Credit or debit'            },
  pago_spei:            { es: 'SPEI',                         en: 'SPEI'                       },
  pago_transferencia:   { es: 'Transferencia',                en: 'Transfer'                   },
  pago_oxxo:            { es: 'OXXO Pay',                     en: 'OXXO Pay'                   },
  pago_tienda:          { es: 'Pago en tienda',               en: 'Pay in store'               },
  pago_datos_tarjeta:   { es: '💳 Datos de la tarjeta',       en: '💳 Card details'            },
  pago_num_tarjeta:     { es: 'Número de tarjeta',            en: 'Card number'                },
  pago_titular:         { es: 'Titular de la tarjeta',        en: 'Cardholder name'            },
  pago_vencimiento:     { es: 'Vencimiento',                  en: 'Expiry'                     },
  pago_ssl:             { es: '🔒  Conexión cifrada SSL · Datos no almacenados', en: '🔒  SSL encrypted · Data not stored' },
  pago_spei_titulo:     { es: '🏦 Instrucciones SPEI',        en: '🏦 Bank transfer instructions' },
  pago_spei_paso1:      { es: 'Abre tu aplicación bancaria',  en: 'Open your banking app'      },
  pago_spei_paso2:      { es: 'Realiza una transferencia SPEI a la siguiente CLABE', en: 'Make a SPEI transfer to the following CLABE' },
  pago_spei_paso3:      { es: 'Usa como referencia tu correo: {email}', en: 'Use your email as reference: {email}' },
  pago_spei_paso4:      { es: 'Presiona "Confirmar" — tu reserva se activa al recibir el pago', en: 'Press "Confirm" — your booking activates upon payment receipt' },
  pago_spei_clabe:      { es: 'CLABE interbancaria',          en: 'Bank CLABE'                 },
  pago_oxxo_titulo:     { es: '🏪 Pago en OXXO',             en: '🏪 Pay at OXXO'             },
  pago_oxxo_paso1:      { es: 'Acude a cualquier tienda OXXO', en: 'Go to any OXXO store'      },
  pago_oxxo_paso2:      { es: 'Indica que realizarás un pago de servicio', en: 'Indicate you want to make a service payment' },
  pago_oxxo_paso3:      { es: 'Proporciona la referencia de pago', en: 'Provide the payment reference' },
  pago_oxxo_paso4:      { es: 'Guarda tu comprobante y presiona "Confirmar"', en: 'Save your receipt and press "Confirm"' },
  pago_oxxo_ref:        { es: 'Referencia de pago',           en: 'Payment reference'          },
  pago_oxxo_monto:      { es: 'Monto: ${precio} MXN · Vigencia 48 h', en: 'Amount: ${precio} MXN · Valid 48 h' },
  pago_btn_pagar:       { es: '🔒  Pagar ahora',              en: '🔒  Pay now'                },
  pago_btn_confirmar:   { es: '✓  Confirmar reserva',         en: '✓  Confirm booking'         },
  pago_sesion_requerida:{ es: 'Sesión requerida',             en: 'Sign in required'           },
  pago_sesion_msg:      { es: 'Inicia sesión para completar tu reserva.', en: 'Sign in to complete your booking.' },
  pago_error:           { es: 'Error',                        en: 'Error'                      },
  pago_error_guardar:   { es: 'No se pudo guardar la reserva. Verifica tu conexión e intenta de nuevo.', en: 'Could not save the booking. Check your connection and try again.' },
  pago_error_inesperado:{ es: 'Error inesperado',             en: 'Unexpected error'           },
  pago_error_pago:      { es: 'Ocurrió un problema al procesar el pago. Intenta de nuevo.', en: 'A problem occurred processing the payment. Please try again.' },
  pago_metodo_tarjeta:  { es: '💳 Tarjeta de crédito/débito', en: '💳 Credit/debit card'       },
  pago_metodo_spei:     { es: '🏦 Transferencia SPEI',        en: '🏦 SPEI Transfer'           },
  pago_metodo_oxxo:     { es: '🏪 OXXO Pay',                  en: '🏪 OXXO Pay'               },

  // ── Confirmación ──────────────────────────────────────────
  conf_titulo:          { es: '¡Reserva confirmada!',         en: 'Booking confirmed!'         },
  conf_subtitulo:       { es: 'Tu aventura por México está lista. Guarda tu folio.', en: 'Your Mexico adventure is ready. Save your reference.' },
  conf_folio:           { es: 'Folio de reserva',             en: 'Booking reference'          },
  conf_detalle:         { es: 'Detalle de tu viaje',          en: 'Trip details'               },
  conf_viajero:         { es: 'Viajero',                      en: 'Traveler'                   },
  conf_telefono:        { es: 'Teléfono',                     en: 'Phone'                      },
  conf_destino:         { es: 'Destino',                      en: 'Destination'                },
  conf_paquete:         { es: 'Paquete',                      en: 'Package'                    },
  conf_fecha:           { es: 'Fecha',                        en: 'Date'                       },
  conf_personas:        { es: 'Personas',                     en: 'People'                     },
  conf_metodo:          { es: 'Método',                       en: 'Method'                     },
  conf_total:           { es: 'Total pagado',                 en: 'Total paid'                 },
  conf_notas:           { es: '📝 Notas del viaje',           en: '📝 Trip notes'              },
  conf_aviso:           { es: '📱  Guarda este folio — lo necesitarás al presentarte en el destino.', en: '📱  Save this reference — you will need it at your destination.' },
  conf_explorar:        { es: 'Explorar más destinos',        en: 'Explore more destinations'  },
  conf_mis_reservas:    { es: 'Ver mis reservas',             en: 'View my bookings'           },

  // ── Detalle ───────────────────────────────────────────────
  det_elige_paquete:    { es: 'Elige tu paquete ideal',       en: 'Choose your ideal package'  },
  det_ver_resenas:      { es: '★ Ver reseñas',                en: '★ View reviews'             },
  det_en_ruta:          { es: '✓ En mi ruta',                 en: '✓ In my route'              },
  det_add_ruta:         { es: '＋ Mi ruta',                   en: '＋ My route'                },
  det_reservar:         { es: 'Reservar →',                   en: 'Book →'                     },
  det_hotel:            { es: '🏨 Hotel',                     en: '🏨 Hotel'                   },
  det_restaurante:      { es: '🍽️ Restaurante',              en: '🍽️ Restaurant'              },
  det_platillo:         { es: 'Platillo recomendado: {p}',    en: 'Recommended dish: {p}'      },
  det_transporte:       { es: '🚗 Transporte',                en: '🚗 Transport'               },
  det_actividades:      { es: '🎯 Actividades incluidas',     en: '🎯 Included activities'     },
  det_add_itinerario:   { es: 'Agregar a un itinerario',      en: 'Add to an itinerary'        },
  det_sin_itinerarios:  { es: 'No tienes itinerarios, crea uno nuevo abajo.', en: 'No itineraries yet, create one below.' },
  det_nuevo_itinerario: { es: 'O crea uno nuevo:',            en: 'Or create a new one:'       },
  det_ej_itinerario:    { es: 'Ej. Vacaciones de Verano',     en: 'E.g. Summer Vacation'       },
  det_crear_agregar:    { es: 'Crear y agregar',              en: 'Create and add'             },
  det_cancelar:         { es: 'Cancelar',                     en: 'Cancel'                     },
  det_quitar:           { es: '(Quitar)',                     en: '(Remove)'                   },
  det_inicia_sesion:    { es: 'Inicia sesión',                en: 'Sign in'                    },
  det_inicia_sesion2:   { es: 'Debes iniciar sesión para agregar a tus rutas.', en: 'You must sign in to add to your routes.' },
  det_incluido:         { es: 'Incluido en paquete',          en: 'Included in package'        },
  det_ubicacion:        { es: '📍 Ubicación',                 en: '📍 Location' },

  // Sistema de Feedback
  feedback_titulo:          { es: 'Calificar viaje a',            en: 'Rate your trip to' },
  feedback_subtitulo:       { es: 'Tu opinión nos ayuda a mejorar', en: 'Your feedback helps us improve' },
  feedback_calificacion_general: { es: 'Calificación general',    en: 'Overall rating' },
  feedback_aspectos:        { es: 'Calificar aspectos',           en: 'Rate aspects' },
  feedback_transporte:      { es: 'Transporte',                   en: 'Transportation' },
  feedback_hotel:           { es: 'Hotel',                        en: 'Hotel' },
  feedback_actividades:     { es: 'Actividades',                  en: 'Activities' },
  feedback_atencion:        { es: 'Atención al cliente',          en: 'Customer service' },
  feedback_precio:          { es: 'Relación precio-calidad',      en: 'Value for money' },
  feedback_comentario:      { es: 'Comentario',                   en: 'Comment' },
  feedback_placeholder_comentario: { es: 'Comparte tu experiencia...', en: 'Share your experience...' },
  feedback_enviar:          { es: 'Enviar reseña',                en: 'Send review' },
  feedback_dejar_resena:    { es: '✨ Dejar reseña',               en: '✨ Leave review' },
  feedback_gracias:         { es: '¡Gracias!',                    en: 'Thank you!' },
  feedback_recibido:        { es: 'Tu reseña ha sido enviada',    en: 'Your review has been sent' },
  feedback_error:           { es: 'Error',                        en: 'Error' },
  feedback_error_envio:     { es: 'No se pudo enviar la reseña',  en: 'Could not send review' },
  feedback_calificacion_requerida: { es: 'Selecciona una calificación', en: 'Select a rating' },
  opcional:                 { es: 'opcional',                     en: 'optional' },
  enviando:                 { es: 'Enviando...',                  en: 'Sending...' },

  // ── Reseñas ───────────────────────────────────────────────
  rsn_titulo:           { es: 'Reseñas',                      en: 'Reviews'                    },
  rsn_sin_resenas:      { es: 'Aún no hay reseñas. ¡Sé el primero!', en: 'No reviews yet. Be the first!' },
  rsn_verificada_singular:{ es: 'reseña verificada',          en: 'verified review'            },
  rsn_verificada_plural:  { es: 'reseñas verificadas',        en: 'verified reviews'           },
  rsn_deja_resena:      { es: 'Deja tu reseña',               en: 'Leave your review'          },
  rsn_placeholder:      { es: 'Cuéntanos tu experiencia...',  en: 'Tell us about your experience...' },
  rsn_gracias:          { es: '✓ ¡Gracias por tu reseña!',    en: '✓ Thanks for your review!'  },
  rsn_publicando:       { es: 'Publicando...',                en: 'Publishing...'              },
  rsn_publicar:         { es: 'Publicar reseña',              en: 'Post review'                },
  rsn_de_viajeros:      { es: 'Reseñas de viajeros',          en: 'Traveler reviews'           },

  // ── Perfil / Configuración ────────────────────────────────
  prf_titulo:           { es: 'Configuración',                en: 'Settings'                   },
  prf_accesos:          { es: 'Accesos rápidos',              en: 'Quick access'               },
  prf_mis_reservas:     { es: 'Mis reservas',                  en: 'My bookings'                },
  prf_historial:        { es: 'Historial',                    en: 'History'                    },
  prf_cuenta:           { es: 'Cuenta',                       en: 'Account'                    },
  prf_editar_perfil:    { es: 'Editar perfil',                en: 'Edit profile'               },
  prf_cambiar_pass:     { es: 'Cambiar contraseña',           en: 'Change password'            },
  prf_preferencias:     { es: 'Preferencias',                 en: 'Preferences'                },
  prf_notificaciones:   { es: 'Notificaciones',               en: 'Notifications'              },
  prf_idioma:           { es: 'Idioma',                       en: 'Language'                   },
  prf_ayuda:            { es: 'Más ayuda',                    en: 'More help'                  },
  prf_centro_ayuda:     { es: 'Centro de ayuda',              en: 'Help center'                },
  prf_acerca:           { es: 'Acerca de Mexcursión',         en: 'About Mexcursión'           },
  prf_admin:            { es: 'Panel de administración',      en: 'Admin panel'                },
  prf_cerrar_sesion:    { es: 'Cerrar sesión',                en: 'Sign out'                   },
  prf_cerrar_confirm:   { es: '¿Deseas cerrar sesión?',       en: 'Do you want to sign out?'   },
  prf_cerrar_sesion_titulo:{ es: 'Cerrar sesión',             en: 'Sign out'                   },
  prf_cancelar:         { es: 'Cancelar',                     en: 'Cancel'                     },
  // Editar perfil
  prf_editar_titulo:    { es: 'Editar perfil',                en: 'Edit profile'               },
  prf_nombre_completo:  { es: 'Nombre completo',              en: 'Full name'                  },
  prf_usuario:          { es: 'Usuario',                      en: 'Username'                   },
  prf_telefono:         { es: 'Teléfono',                     en: 'Phone'                      },
  prf_ph_nombre:        { es: 'Tu nombre',                    en: 'Your name'                  },
  prf_ph_usuario:       { es: 'Tu usuario',                   en: 'Your username'              },
  prf_ph_telefono:      { es: '10 dígitos',                   en: '10 digits'                  },
  prf_guardar:          { es: 'Guardar cambios',              en: 'Save changes'               },
  prf_err_nombre:       { es: 'Nombre y usuario son obligatorios', en: 'Name and username are required' },
  prf_perfil_ok:        { es: 'Perfil actualizado correctamente', en: 'Profile updated successfully' },
  // Cambiar contraseña
  prf_pass_titulo:      { es: 'Cambiar contraseña',           en: 'Change password'            },
  prf_pass_actual:      { es: 'Contraseña actual',            en: 'Current password'           },
  prf_pass_nueva:       { es: 'Nueva contraseña',             en: 'New password'               },
  prf_pass_confirmar:   { es: 'Confirmar nueva contraseña',   en: 'Confirm new password'       },
  prf_btn_pass:         { es: 'Actualizar contraseña',        en: 'Update password'            },
  prf_err_pass_actual:  { es: 'Ingresa tu contraseña actual', en: 'Enter your current password'},
  prf_err_pass_corta:   { es: 'La nueva contraseña debe tener al menos 6 caracteres', en: 'New password must be at least 6 characters' },
  prf_err_pass_match:   { es: 'Las contraseñas no coinciden', en: 'Passwords do not match'    },
  prf_pass_ok:          { es: 'Contraseña actualizada correctamente', en: 'Password updated successfully' },
  // Notificaciones
  prf_notif_push:       { es: 'Notificaciones push',          en: 'Push notifications'         },
  prf_notif_desc:       { es: 'Recibir alertas de nuevos destinos y ofertas', en: 'Receive alerts for new destinations and offers' },
  prf_notif_on:         { es: 'Activadas',                     en: 'Enabled'                    },
  prf_notif_off:        { es: 'Desactivadas',                  en: 'Disabled'                   },
  prf_notif_estado:     { es: 'Notificaciones:',              en: 'Notifications:'             },
  // Idioma
  prf_idioma_titulo:    { es: 'Idioma',                       en: 'Language'                   },
  prf_idioma_es:        { es: 'Español',                      en: 'Spanish'                 },
  prf_idioma_en:        { es: 'English',                      en: 'English'                 },
  // Tema
  prf_tema:             { es: 'Tema',                         en: 'Theme'                     },
  prf_tema_titulo:      { es: 'Tema de la app',               en: 'App theme'                 },
  prf_tema_oscuro:      { es: 'Modo oscuro',                  en: 'Dark mode'                 },
  prf_tema_desc:        { es: 'Cambiar entre tema claro y oscuro', en: 'Switch between light and dark theme' },
  prf_tema_on:          { es: 'Activado',                      en: 'Enabled'                    },
  prf_tema_off:         { es: 'Desactivado',                   en: 'Disabled'                   },
  prf_tema_estado:      { es: 'Tema oscuro:',                 en: 'Dark theme:'               },
  // Ayuda
  prf_ayuda_titulo:     { es: 'Centro de ayuda',              en: 'Help center'                },
  prf_ayuda_p1:         { es: '¿Cómo agrego un destino a favoritos?', en: 'How do I add a destination to favorites?' },
  prf_ayuda_r1:         { es: 'Presiona el ícono de corazón en cualquier tarjeta de destino desde la pantalla de inicio.', en: 'Tap the heart icon on any destination card from the home screen.' },
  prf_ayuda_p2:         { es: '¿Cómo creo una ruta?',         en: 'How do I create a route?'   },
  prf_ayuda_r2:         { es: 'Ve a la sección Rutas, presiona "+" en los destinos que quieras y luego accede a "Mi ruta".', en: 'Go to Routes, tap "+" on the destinations you want, then go to "My route".' },
  prf_ayuda_p3:         { es: '¿Puedo cambiar mi información?', en: 'Can I change my information?' },
  prf_ayuda_r3:         { es: 'Sí, ve a Configuración → Editar perfil para actualizar tu nombre, usuario y teléfono.', en: 'Yes, go to Settings → Edit profile to update your name, username, and phone.' },
  prf_ayuda_p4:         { es: '¿Cómo cambio mi contraseña?',  en: 'How do I change my password?' },
  prf_ayuda_r4:         { es: 'Ve a Configuración → Cambiar contraseña e ingresa tu contraseña actual y la nueva.', en: 'Go to Settings → Change password and enter your current and new password.' },
  prf_ayuda_p5:         { es: '¿Los datos se guardan?',       en: 'Is my data saved?'          },
  prf_ayuda_r5:         { es: 'Sí, tu cuenta, favoritos y rutas se guardan localmente en tu dispositivo con SQLite.', en: 'Yes, your account, favorites, and routes are saved locally on your device with SQLite.' },
  // Acerca
  prf_acerca_titulo:    { es: 'Acerca de Mexcursión',         en: 'About Mexcursión'           },
  prf_acerca_version:   { es: 'Versión 1.0.0',                en: 'Version 1.0.0'              },
  prf_acerca_desc:      { es: 'Mexcursión es tu guía de viaje para descubrir los mejores destinos de México. Desde playas paradisíacas hasta zonas arqueológicas, te ayudamos a planear tu aventura perfecta.', en: 'Mexcursión is your travel guide to discover the best destinations in Mexico. From paradise beaches to archaeological sites, we help you plan your perfect adventure.' },
  prf_acerca_copy:      { es: '© 2025 Mexcursión · Todos los derechos reservados', en: '© 2025 Mexcursión · All rights reserved' },

  // ── Rutas — vista principal ───────────────────────────────
  rut_mis_viajes:           { es: 'Mis viajes',                                              en: 'My trips'                                          },
  rut_mis_viajes_sub:       { es: 'Organiza y planea tus rutas por México',                  en: 'Organize and plan your routes through Mexico'      },
  rut_nuevo_viaje:          { es: '+ Nuevo viaje',                                           en: '+ New trip'                                        },
  rut_cargando:             { es: 'Cargando tus viajes...',                                  en: 'Loading your trips...'                             },
  rut_sin_viajes:           { es: 'Aún no tienes viajes',                                    en: 'No trips yet'                                      },
  rut_sin_viajes2:          { es: 'Crea tu primer itinerario y empieza a agregar destinos desde el catálogo.', en: 'Create your first itinerary and start adding destinations from the catalog.' },
  rut_crear_primer:         { es: 'Crear primer viaje',                                      en: 'Create first trip'                                 },
  rut_sin_destinos_aun:     { es: 'Sin destinos aún',                                        en: 'No destinations yet'                               },
  rut_ver_itinerario:       { es: 'Ver itinerario',                                          en: 'View itinerary'                                    },
  rut_duplicar:             { es: 'Duplicar',                                                en: 'Duplicate'                                         },
  rut_compartir:            { es: 'Compartir',                                               en: 'Share'                                             },
  rut_eliminar:             { es: 'Eliminar',                                                en: 'Delete'                                            },
  rut_confirmar_borrar:     { es: 'Eliminar "{nombre}"? Esta acción no se puede deshacer.',  en: 'Delete "{nombre}"? This action cannot be undone.' },
  // ── Rutas — vista detalle ─────────────────────────────────
  rut_editar:               { es: 'Editar',                                                  en: 'Edit'                                              },
  rut_destino_singular:     { es: 'destino',                                                 en: 'destination'                                       },
  rut_destino_plural:       { es: 'destinos',                                                en: 'destinations'                                      },
  rut_dia_singular:         { es: 'día',                                                     en: 'day'                                               },
  rut_dia_plural:           { es: 'días',                                                    en: 'days'                                              },
  rut_por_persona:          { es: 'por persona',                                             en: 'per person'                                        },
  rut_por_persona_cap:      { es: 'Por persona',                                             en: 'Per person'                                        },
  rut_pp:                   { es: 'p/p',                                                     en: 'p.p.'                                              },
  rut_fecha_inicio:         { es: 'Fecha de inicio',                                         en: 'Start date'                                        },
  rut_fecha_fijar:          { es: 'Toca para fijar una fecha',                               en: 'Tap to set a date'                                 },
  rut_eliminar_viaje:       { es: 'Eliminar viaje',                                          en: 'Delete trip'                                       },
  rut_confirmar:            { es: 'Confirmar',                                               en: 'Confirm'                                           },
  rut_cancelar:             { es: 'Cancelar',                                                en: 'Cancel'                                            },
  rut_guardar:              { es: 'Guardar',                                                 en: 'Save'                                              },
  rut_presupuesto:          { es: 'Presupuesto estimado',                                    en: 'Estimated budget'                                  },
  rut_num_viajeros:         { es: 'Número de viajeros',                                      en: 'Number of travelers'                               },
  rut_total_viajeros:       { es: 'Total ({n} viajeros)',                                    en: 'Total ({n} travelers)'                             },
  rut_desglose:             { es: 'Desglose por destino',                                    en: 'Breakdown by destination'                          },
  rut_total_label:          { es: 'total',                                                   en: 'total'                                             },
  rut_precio_nota:          { es: '* Precios estimados por persona. Pueden variar según disponibilidad y temporada.', en: '* Estimated prices per person. May vary based on availability and season.' },
  rut_sin_destinos:         { es: 'Sin destinos',                                            en: 'No destinations'                                   },
  rut_sin_destinos2:        { es: 'Agrega destinos desde las rutas sugeridas o el catálogo de destinos.', en: 'Add destinations from suggested routes or the destination catalog.' },
  rut_explorar:             { es: 'Explorar destinos',                                       en: 'Explore destinations'                              },
  rut_relacionados:         { es: 'Destinos que te pueden gustar',                           en: 'Destinations you may like'                         },
  rut_relacionados_sub:     { es: 'Basado en los estilos de tu ruta',                        en: 'Based on your route styles'                        },
  // ── Rutas — modales ───────────────────────────────────────
  rut_renombrar_titulo:     { es: 'Renombrar viaje',                                         en: 'Rename trip'                                       },
  rut_renombrar_sub:        { es: 'Escribe el nuevo nombre para este itinerario',             en: 'Enter the new name for this itinerary'             },
  rut_ph_nombre_viaje:      { es: 'Nombre del viaje...',                                     en: 'Trip name...'                                      },
  rut_modal_nuevo_titulo:   { es: 'Nuevo viaje',                                             en: 'New trip'                                          },
  rut_modal_nuevo_sub:      { es: 'Dale un nombre a tu próximo itinerario',                  en: 'Give a name to your next itinerary'                },
  rut_ph_ejemplo:           { es: 'Por ejemplo: Ruta por el sureste',                        en: 'E.g. Route through the southeast'                  },
  rut_crear_viaje:          { es: 'Crear viaje',                                             en: 'Create trip'                                       },
  rut_agregar_viaje_titulo: { es: 'Agregar a un viaje',                                      en: 'Add to a trip'                                     },
  rut_agregar_viaje_sub:    { es: 'Elige un itinerario existente o crea uno nuevo',          en: 'Choose an existing itinerary or create a new one'  },
  rut_agregar_btn:          { es: 'Agregar',                                                 en: 'Add'                                               },
  rut_o_crear_nuevo:        { es: 'o crea un nuevo viaje',                                   en: 'or create a new trip'                              },
  rut_ph_nuevo_viaje:       { es: 'Nombre del nuevo viaje...',                               en: 'New trip name...'                                  },
  rut_crear_y_agregar:      { es: 'Crear viaje y agregar',                                   en: 'Create trip and add'                               },
  rut_cuando_viaje:         { es: '¿Cuándo empieza este viaje?',                             en: 'When does this trip start?'                        },
  rut_dia_picker:           { es: 'Día',                                                     en: 'Day'                                               },
  rut_mes_picker:           { es: 'Mes',                                                     en: 'Month'                                             },
  rut_anio_picker:          { es: 'Año',                                                     en: 'Year'                                              },
  rut_agregar_itinerario:   { es: 'Agregar a un itinerario',                                 en: 'Add to an itinerary'                               },
  // ── Rutas — rutas sugeridas ───────────────────────────────
  rut_sugeridas:            { es: 'Rutas sugeridas',                                         en: 'Suggested routes'                                  },
  rut_sugeridas_sub:        { es: 'Selecciona una para ver todos los detalles y agregarla a un viaje', en: 'Select one to view all details and add it to a trip' },
  rut_buscar_ph:            { es: 'Buscar por destino, estado o estilo...',                  en: 'Search by destination, state or style...'          },
  rut_todos:                { es: 'Todos',                                                   en: 'All'                                               },
  rut_economico:            { es: 'Económico',                                               en: 'Budget'                                            },
  rut_medio:                { es: 'Medio',                                                   en: 'Standard'                                          },
  rut_premium:              { es: 'Premium',                                                 en: 'Premium'                                           },
  rut_sin_resultados_q:     { es: 'Sin resultados para "{q}"',                               en: 'No results for "{q}"'                              },
  rut_sin_nivel:            { es: 'Sin rutas en este nivel',                                 en: 'No routes at this level'                           },
  // ── Rutas — toasts ────────────────────────────────────────
  rut_toast_creado:         { es: 'Viaje creado',                                            en: 'Trip created'                                      },
  rut_toast_duplicado:      { es: 'Viaje duplicado',                                         en: 'Trip duplicated'                                   },
  rut_toast_eliminado:      { es: 'Viaje eliminado',                                         en: 'Trip deleted'                                      },
  rut_toast_renombrado:     { es: 'Viaje renombrado',                                        en: 'Trip renamed'                                      },
  rut_toast_agregado:       { es: 'Destino agregado al viaje',                               en: 'Destination added to trip'                         },
  rut_toast_creado_agr:     { es: 'Viaje creado y destino agregado',                         en: 'Trip created and destination added'                },
  rut_toast_copiado:        { es: 'Copiado al portapapeles',                                 en: 'Copied to clipboard'                               },
  // ── Rutas — tarjeta de etapa ──────────────────────────────
  rut_alojamiento:          { es: 'Alojamiento',                                             en: 'Accommodation'                                     },
  rut_gastronomia:          { es: 'Gastronomía',                                             en: 'Gastronomy'                                        },
  rut_especialidad:         { es: 'Especialidad: {p}',                                       en: 'Specialty: {p}'                                    },
  rut_actividades_inc:      { es: 'Actividades incluidas',                                   en: 'Included activities'                               },
  rut_transporte_rec:       { es: 'Transporte recomendado',                                  en: 'Recommended transport'                             },
  rut_costo_persona:        { es: 'Costo estimado por persona',                              en: 'Estimated cost per person'                         },
  rut_subir:                { es: 'Subir',                                                   en: 'Up'                                                },
  rut_bajar:                { es: 'Bajar',                                                   en: 'Down'                                              },
  rut_quitar:               { es: 'Quitar',                                                  en: 'Remove'                                            },
  rut_dia_num:              { es: 'Día {n}',                                                 en: 'Day {n}'                                           },
  rut_dias_rango:           { es: 'Días {n1} – {n2}',                                        en: 'Days {n1} – {n2}'                                  },
  // ── Rutas — texto para compartir ─────────────────────────
  rut_comp_app:             { es: 'Planificado con Mexcursion',                              en: 'Planned with Mexcursion'                           },
  rut_comp_aloj:            { es: '   Alojamiento: {h}',                                    en: '   Accommodation: {h}'                             },
  rut_comp_gastro:          { es: '   Gastronomia: {r}',                                    en: '   Gastronomy: {r}'                                },
  rut_comp_duracion:        { es: 'Duracion total: {n} dias',                               en: 'Total duration: {n} days'                          },
  rut_comp_costo_pp:        { es: 'Costo por persona: {c}',                                 en: 'Cost per person: {c}'                              },
  rut_comp_total:           { es: 'Total ({n} viajeros): {c}',                              en: 'Total ({n} travelers): {c}'                        },
  rut_en_iti:               { es: '✓ En tu ruta',                                            en: '✓ In your trip'                                    },
  rut_fecha_ico:            { es: 'Fecha',                                                   en: 'Date'                                              },
  rut_duracion_rec:         { es: 'Duración recomendada: {n} {u}',                           en: 'Recommended duration: {n} {u}'                     },
  // ── Rutas — keys nuevas para rutas.tsx ───────────────────
  rut_sesion_requerida:     { es: 'Sesión requerida',                                        en: 'Sign in required'                                  },
  rut_sesion_msg:           { es: 'Inicia sesión para gestionar tus rutas',                  en: 'Sign in to manage your routes'                     },
  rut_ir:                   { es: 'Ir',                                                      en: 'Go'                                                },
  rut_toast_agregado_msg:   { es: 'El destino fue añadido a tu itinerario.',                 en: 'The destination was added to your itinerary.'      },
  rut_toast_creado_agr_msg: { es: 'Se creó el itinerario y se agregó el destino.',           en: 'The itinerary was created and the destination was added.' },
  rut_eliminar_viaje_titulo:{ es: '🗑 Eliminar viaje',                                       en: '🗑 Delete trip'                                     },
  rut_eliminar_viaje_msg:   { es: '¿Quieres borrar este itinerario por completo?',           en: 'Do you want to delete this itinerary?'             },
  rut_compartir_btn:        { es: '📤 Compartir',                                            en: '📤 Share'                                          },
  rut_borrar_viaje_btn:     { es: '🗑 Borrar viaje',                                         en: '🗑 Delete trip'                                     },
  rut_viaje_vacio:          { es: 'Viaje vacío',                                             en: 'Empty trip'                                        },
  rut_viaje_vacio_msg:      { es: 'Explora destinos en la app y agrégalos a este viaje con el botón "Mi Ruta".', en: 'Explore destinations and add them to this trip with the "My Route" button.' },
  rut_mis_itinerarios:      { es: 'Mis Itinerarios',                                         en: 'My Itineraries'                                    },
  rut_mis_viajes_hero:      { es: 'Mis Viajes ✈️',                                           en: 'My Trips ✈️'                                       },
  rut_mis_viajes_hero_sub:  { es: 'Organiza, planea y comparte tus aventuras por México',   en: 'Organize, plan and share your adventures through Mexico' },
  rut_nuevo_viaje_btn:      { es: '+ Crear nuevo viaje',                                    en: '+ Create new trip'                                 },
  rut_inspiracion:          { es: 'Inspiración para tu próximo viaje',                       en: 'Inspiration for your next trip'                    },
  rut_nuevo_iti_titulo:     { es: '✈️ Nuevo Itinerario',                                     en: '✈️ New Itinerary'                                   },
  rut_nuevo_iti_sub:        { es: '¿Cómo se llama tu próxima aventura?',                    en: 'What is your next adventure called?'               },
  rut_ph_nombre_iti:        { es: 'Ej. Vacaciones en la playa 🏖️',                          en: 'E.g. Beach vacation 🏖️'                            },
  rut_agregar_iti_sub2:     { es: 'Elige un itinerario o crea uno nuevo',                   en: 'Choose an itinerary or create a new one'           },
  rut_o_crear_sep:          { es: '— o crea un nuevo viaje —',                              en: '— or create a new trip —'                          },
  rut_ph_nuevo_iti:         { es: 'Nombre del nuevo itinerario...',                          en: 'New itinerary name...'                             },
  rut_destinos:             { es: 'destinos',                                                en: 'destinations'                                      },
  rut_destino:              { es: 'destino',                                                 en: 'destination'                                       },
  rut_comp_titulo:          { es: '🗺️ *Mi Itinerario: {nombre}*',                            en: '🗺️ *My Itinerary: {nombre}*'                       },
  rut_comp_duracion2:       { es: '⌛ Duración: ~{n} días',                                  en: '⌛ Duration: ~{n} days'                             },
  rut_comp_costo2:          { es: '💰 Costo aprox: ${c} MXN',                               en: '💰 Approx cost: ${c} MXN'                          },
  rut_comp_footer:          { es: '¡Planeado con Mexcursion!',                               en: 'Planned with Mexcursion!'                          },
  rut_sin_itis_aun:         { es: 'Sin itinerarios aún',                                     en: 'No itineraries yet'                                },
  rut_sin_itis_msg:         { es: 'Crea tu primer viaje y empieza a agregar destinos desde el catálogo.', en: 'Create your first trip and start adding destinations from the catalog.' },
} as const;

export type TraduccionClave = keyof typeof T;

// Mapas planos precalculados una sola vez al cargar el módulo.
// Cambiar de idioma = swap de referencia, sin ningún cómputo adicional.
type MapaPlano = Record<TraduccionClave, string>;
export const TEXTOS: Record<Idioma, MapaPlano> = {
  es: Object.fromEntries(Object.entries(T).map(([k, v]) => [k, v.es])) as MapaPlano,
  en: Object.fromEntries(Object.entries(T).map(([k, v]) => [k, v.en])) as MapaPlano,
};

/** Devuelve el string en el idioma solicitado, con soporte de interpolación {var} */
export function traducir(clave: TraduccionClave, idioma: Idioma, vars?: Record<string, string | number>): string {
  let txt = TEXTOS[idioma][clave] ?? clave;
  if (vars) for (const [k, v] of Object.entries(vars)) txt = txt.replaceAll(`{${k}}`, String(v));
  return txt;
}
